# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"CsvValidityAssessment": "00_core.ipynb",
         "validate_csv_from_azure_blob_storage": "00_core.ipynb",
         "validate_csv_string": "00_core.ipynb",
         "validate_csv_file": "00_core.ipynb",
         "validate_csv": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://christopheralcock.github.io/csv_validate_nbdev/"

git_url = "https://github.com/christopheralcock/csv_validate_nbdev/tree/Master/"

def custom_doc_links(name): return None
